Frontend/toplevelsearchrework
ClinicalTrialsTeam/ctfrontier pull request #15
Opened 2021-03-20 16:10 UTC by elarens

Pre-customer presentation updates

2021-03-20 23:02 UTC, nataliemona approved these changes

2021-03-20 23:02 UTC, nataliemona commented on frontend/src/components/molecules/BasicSearchAccordion/BasicSearchAccordion.js
> +      <>
Is this supposed to be here?

2021-03-20 23:02 UTC, nataliemona commented on frontend/src/components/organisms/ListViewTable/ListViewTable.js
> +    console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
If you don't need the console statement anymore, then I would remove it to get rid of the warning.

2021-03-20 23:02 UTC, nataliemona commented on frontend/src/components/organisms/ListViewTable/ListViewTableConfig.js
> +    status: 'Recruting',
Recruiting misspelled

2021-03-20 23:02 UTC, nataliemona commented on frontend/src/components/organisms/NewForm/NewForm.js
> +      console.log(err);
Maybe another way to do these would be with logging library if you want to keep them in https://www.loggly.com/blog/best-practices-for-client-side-logging-and-error-handling-in-react/

2021-03-20 23:10 UTC, bapower reviewed
You have several warnings in the console on page load
<img width="1552" alt="Screen Shot 2021-03-20 at 21 58 12" src="https://user-images.githubusercontent.com/11981100/111888080-3d077080-89d1-11eb-81e7-49914d07f41f.png">

2021-03-20 23:10 UTC, bapower commented on frontend/src/components/atoms/logos/CommonLogo/CommonLogo.js
> +function CommonLogo() {
You already have a logo component, you don't need another one. You can pass the src, class and alt text as props from the parent component so you can re-use the same component for all logos.

2021-03-20 23:10 UTC, bapower commented on frontend/src/components/molecules/BasicSearchAccordion/BasicSearchAccordion.js
> +                  label="Intervention / treatment"
Use the TextInputField component for these text inputs.

2021-03-20 23:10 UTC, bapower commented on frontend/src/components/organisms/NewForm/NewForm.js
> +  recruitment, access, countries,
Use the country API to get the countries that have clinical trials from the database.

2021-03-20 23:10 UTC, bapower commented on frontend/src/components/organisms/ListViewTable/ListViewTable.js
> +    console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
Remove debugging code.

2021-03-20 23:10 UTC, bapower commented on frontend/src/components/organisms/NewForm/NewForm.js
> +import React, { Component } from 'react';
NewForm is not a good name for a component. It is not very meaningful or descriptive.

2021-03-20 23:10 UTC, bapower commented on frontend/src/components/views/AltTopLevelSearchView/AltTopLevelSearchView.js
> +  render() {
AltTopLevelSearch view is not a very good name for a component. It is not meaningful or descriptive

2021-03-20 23:10 UTC, bapower commented on frontend/src/components/organisms/NewForm/NewForm.js
> +                  clickHandler={this.handleClear}
This is the wrong click handler. It should be a new one for expanding advanced options, not handleClear.

2021-03-20 23:21 UTC, bapower requested changes
You have several warnings in the console on page load
<img width="1552" alt="Screen Shot 2021-03-20 at 21 58 12" src="https://user-images.githubusercontent.com/11981100/111888272-03376980-89d3-11eb-9b95-2b15a3e113af.png">

2021-03-20 23:22 UTC, nataliemona commented on frontend/src/index.js
> +  <BrowserRouter>
I think you should actually keep the `<React.StrictMode>` here and put the Router in App.js

2021-03-21 00:41 UTC, elarens commented on frontend/src/components/organisms/NewForm/NewForm.js
> +                  clickHandler={this.handleClear}
I agree. It was a placeholder. I will remove it for now. Someone needs to implement this function, and we should discus who it should be

2021-03-21 00:41 UTC, elarens commented on frontend/src/components/organisms/NewForm/NewForm.js
> +  recruitment, access, countries,
Why should I use the country API? What is the benefit?

2021-03-21 01:42 UTC, bragu commented on frontend/src/components/organisms/NewForm/NewForm.js
> +  recruitment, access, countries,
Country API gets countries from database where clinical studies are conducted. It will help rather displaying a static list.

2021-03-21 21:52 UTC, bapower commented on frontend/src/components/organisms/NewForm/NewForm.js
> +  recruitment, access, countries,
Yes we only want to list the countries that have clinical trials in them. This should probably be a separate story though.

2021-03-22 22:42 UTC, bapower approved these changes

2021-03-22 22:53 UTC, merged